"""empty message

Revision ID: 13169ddbdb81
Revises: 43292873af39
Create Date: 2024-05-12 22:10:01.815132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13169ddbdb81'
down_revision = '43292873af39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reservation_service_id', 'service', ['service_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reservation_service_id', type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
