"""Actualizar modelos de datos

Revision ID: 4d622add1ac5
Revises: d4b2dccf7ecb
Create Date: 2024-05-26 15:56:10.847602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d622add1ac5'
down_revision = 'd4b2dccf7ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        # Agrega los nombres reales de las restricciones de foreign key aquí
        batch_op.drop_constraint('fk_reservation_proveedor_id', type_='foreignkey')
        batch_op.drop_constraint('fk_reservation_paquete_evento_id', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_reservation_paquete_evento_id', 'profile', ['paquete_evento_id'], ['id'])
        batch_op.create_foreign_key('fk_reservation_proveedor_id', 'event_pack', ['proveedor_id'], ['id'])

    # ### end Alembic commands ###
