"""Agregando guests a  Event model

Revision ID: 983cb167deb8
Revises: 3a03bb35acc0
Create Date: 2024-05-14 09:50:47.331191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983cb167deb8'
down_revision = '3a03bb35acc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guests', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('guests')

    # ### end Alembic commands ###
