"""Adding created_at to Service

Revision ID: c0003a0f0751
Revises: 986b4bdee3b5
Create Date: 2024-05-25 01:16:29.127734

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone

# revision identifiers, used by Alembic.
revision = 'c0003a0f0751'
down_revision = '986b4bdee3b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               nullable=False,
               server_default=sa.func.now())

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###

    # Remove the default value after adding the column
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('created_at', server_default=None)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('created_at', server_default=None)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('created_at', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               nullable=True,
               server_default=None)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('created_at')
    # ### end Alembic commands ###