"""editing created_at reservations table

Revision ID: d4b2dccf7ecb
Revises: c0003a0f0751
Create Date: 2024-05-26 15:37:48.628433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b2dccf7ecb'
down_revision = 'c0003a0f0751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('date_time_reservation',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('precio',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('proveedor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('paquete_evento_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_reservation_proveedor_id', 'profile', ['proveedor_id'], ['id'])
        batch_op.create_foreign_key('fk_reservation_paquete_evento_id', 'event_pack', ['paquete_evento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reservation_paquete_evento_id', type_='foreignkey')
        batch_op.drop_constraint('fk_reservation_proveedor_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_reservation_paquete_evento_id_old', 'profile', ['paquete_evento_id'], ['id'])
        batch_op.create_foreign_key('fk_reservation_proveedor_id_old', 'event_pack', ['proveedor_id'], ['id'])
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('paquete_evento_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('proveedor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('precio',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('date_time_reservation',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('created_at')
    # ### end Alembic commands ###
